### ISSUE TITLE
argument must be of type string -- Error for Window

### ISSUE THREAD

**Issue by callppatel** [outsideris/citizen#32]
{"level":50,"time":1550501838893,"msg":"The \"path\" argument must be of type string. Received type undefined","pid":18928,"hostname":"CPX-8SV0UT1ABW5","name":"citizen","type":"Error","stack":"TypeError [ERR_INVALID_ARG_TYPE]: The \"path\" argument must be of type string. Received type undefined\n    at assertPath (path.js:39:11)\n    at join (path.js:434:7)\n    at hasModule (C:\\snapshot\\citizen\\storages\\file.js:0:0)\n    at Form.router.post.form.on (C:\\snapshot\\citizen\\routes\\modules.js:0:0)\n    at Form.emit (events.js:182:13)\n    at C:\\snapshot\\citizen\\node_modules\\multiparty\\index.js:579:12\n    at process._tickCallback (internal/process/next_tick.js:61:11)","v":1}
{"level":50,"time":1550501838894,"msg":"TypeError [ERR_INVALID_ARG_TYPE]: The \"path\" argument must be of type string. Received type undefined\n    at assertPath (path.js:39:11)\n    at join (path.js:434:7)\n    at hasModule (C:\\snapshot\\citizen\\storages\\file.js:0:0)\n    at Form.router.post.form.on (C:\\snapshot\\citizen\\routes\\modules.js:0:0)\n    at Form.emit (events.js:182:13)\n    at C:\\snapshot\\citizen\\node_modules\\multiparty\\index.js:579:12\n    at process._tickCallback (internal/process/next_tick.js:61:11)","pid":18928,"hostname":"CPX-8SV0UT1ABW5","name":"citizen","v":1}
POST /v1/modules/dev-team/acn/aws/0.0.3 500 16.815 ms - 84

I have all environment paramter set
CITIZEN_ADDR=https://f7b9f89b.ngrok.io
CITIZEN_AWS_S3_BUCKET=terraforms3module
CITIZEN_DATA_PATH=C:\snapshot\citizen\storages
CITIZEN_STORAGE=s3
CITIZEN_STORAGE_PATH=C:\Terraform-Citizen\data

**Comment by outsideris** [comment]
I will check it on Windows. Can you provide your environment? e.g window version or node.js version.

**Comment by darrylb-github** [comment]
@callppatel I think this is due to windows paths using `\` vs `/` and therefore needing escaped.

```
$ export CITIZEN_STORAGE_PATH=C:\Terraform-Citizen\data
$ echo CITIZEN_STORAGE_PATH
C:Terraform-Citizendata
$ export CITIZEN_STORAGE_PATH=C:\\Terraform-Citizen\\data
$ echo CITIZEN_STORAGE_PATH
C:\Terraform-Citizen\data
```

Got the same error message when I hadn't set the `CITIZEN_DATA_PATH` environment variable on mac OS which led me to this issue.
